name: Déploiement sur Azure VM

on:
    push:
        branches:
            - main # Déclenche le déploiement uniquement pour la branche main

jobs:
    deploy:
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout du code
              uses: actions/checkout@v3

            - name: Déployer sur Azure VM
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.AZURE_VM_IP }} # Adresse IP de la VM Azure
                  username: ${{ secrets.AZURE_VM_USERNAME }} # Nom d'utilisateur SSH
                  key: ${{ secrets.AZURE_VM_SSH_KEY }} # Clé SSH privée
                  token: ${{ secrets.ACCESS_TOKEN }} # Token d'accès
                  script: |
                      cd /home/azureuser
                      if [ -d "Discord-Bot" ]; then
                        cd Discord-Bot
                        git fetch --all
                        git reset --hard origin/main
                      else
                        git clone https://github.com/Ilian92/Discord-Bot.git Discord-Bot
                        cd Discord-Bot
                      fi
                      source venv/bin/activate
                      pip install -r requirements.txt
